WebApplication2/Controllers/StudentProfileController.cs
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class StudentProfileController : Controller
    {
        // GET: StudentProfile
        public ActionResult Index()
        {
            return View();
        }

        // GET: StudentProfile/Details
        public ActionResult Details()
        {
            StudentProfile profile = new StudentProfile {FirstName="Rohit",LastName="Dumbre",CWID="10406746",EmailID="Rohit@gmail.com",Number="2011001000",Gender="Male"};
            return View(profile);
        }

        // GET: StudentProfile/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentProfile/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentProfile/Edit
        public ActionResult Edit()
        {
            return View();
        }

        // POST: StudentProfile/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentProfile/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StudentProfile/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication2/Controllers/profileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class profileController : Controller
    {
        // GET: profile
        public ActionResult Index()
        {
            return View();
        }

        // GET: profile/Details
        public ActionResult Details()
        {
            return View();
        }

        // GET: profile/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: profile/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: profile/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: profile/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: profile/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: profile/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication2/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Profile", "Index", "Home")</li>
                    <li>@Html.ActionLink("Dashboard", "About", "Home")</li>
                    <li>@Html.ActionLink("My Study Plan", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Details", "Details", "profile")</li>

                </ul>

            </div>
        </div>
    </div>

    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Study Plan</p>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Study Plan</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Study Plan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                   
                    <li>@Html.ActionLink("MyProfile", "Details", "StudentProfile")</li>
                    
                    <li>@Html.ActionLink("Dashboard", "Create", "Dashboard")</li>

                </ul>
              @Html.Partial("_LoginPartial")
                
            </div>
        </div>
    </div>
   
   
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Study Plan</p>
        </footer>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>