WebApplication2/Models/Dashboard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Dashboard
    {
        public string Course { get; set; }
        public string  Concentration { get; set; }
        public string  Semester { get; set; }
        [Display(Name = "No of Semesters")]
        public string NumberofSemesters { get; set; }
        public string  Elective { get; set; }
    }
}

WebApplication2/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

        // GET: Dashboard/Details
        public ActionResult Details()
        {
            return View();
        }

        // GET: Dashboard/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Edit
        public ActionResult Edit()
        {
            return View();
        }

        // POST: Dashboard/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dashboard/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication2/Controllers/StudyPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class StudyPlanController : Controller
    {
        // GET: StudyPlan
        public ActionResult Index()
        {
            return View();
        }

        // GET: StudyPlan/Details/5
        public ActionResult Details()
        {
            return View();
        }

        // GET: StudyPlan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudyPlan/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: StudyPlan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StudyPlan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: StudyPlan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StudyPlan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication2/Views/Dashboard/Create.cshtml
@model WebApplication2.Models.Dashboard

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="pad" class="row">
        <div class="col-md-1">
            <img src="~/Content/images/Studyplan.png" width="350" height="150" />
        </div>
        <div class="col-md-6 col-md-offset-2" style="color :forestgreen">

            <div class="form-horizontal">
                <h2>Dashboard</h2>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Course", new List<SelectListItem>
            {
            new SelectListItem { Text="Computer Science", Value="1"},
            new SelectListItem { Text="Information Systems", Value="2"},
            new SelectListItem { Text="Computer Engineering", Value="3"},
            new SelectListItem { Text="Construction Management", Value="4"},
            new SelectListItem { Text="Electrical Engineering", Value="5"},

            }, "Select Course")
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Concentration, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Concentration, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Concentration, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2"  style="color :black">
                        @Html.RadioButton("Semester", "Fall")  Fall
                    </div>
                    <div class="col-md-2"  style="color :black">
                        @Html.RadioButton("Semester", "Spring") Spring

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NumberofSemesters, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2"  style="color :black">
                        @Html.RadioButton("NumOfSemester", "3")  3
                    </div>

                    <div class="col-md-2"  style="color :black">
                        @Html.RadioButton("NumOfSemester", "4") 4
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Elective, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Elective, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Elective, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        @Html.ActionLink("Cancel", "MyHome", "Home", null, new { @class = "btn btn-default" })
                    </div>

                    <div class="col-md-2">
                        <input type="reset" value="Reset" class="btn btn-default" onclick="onreset" />
                    </div>

                    <div class="col-md-2">
                        @Html.ActionLink("Submit", "Details", "StudyPlan", null, new { @class = "btn btn-default" })
                        @*<input type="submit" value="Submit" class="btn btn-default"  />*@
                    </div>
                </div>
            </div>
            </div>
        </div>

            }

       